name: Testing

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start app
        run: make setup

      - name: Integration test
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman-collections/fiber-versioning-boilerplate.postman_collection.json
          environment: postman-collections/fiber-versioning-boilerplate.postman_environment.json
          reporters: cli